#!/usr/bin/sh

pkill sxhkd
sxhkd &

xsetroot -cursor_name left_ptr &
dunst -conf ~/.config/dunst/dunstrc &
picom --config ~/.config/bspwm/picom.conf &
dunst -conf ~/.config/dunst/dunstrc &

#$HOME/.fehbg &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
$HOME/.config/bspwm/scripts/low_bat_notifier.sh &

xfce4-power-manager &
nm-applet --no-agent &
xsetroot -cursor_name left_ptr &
setxkbmap -option grp:alt_shift_toggle us


bspc monitor -d I II III IV V VI VII


bspc config border_width         2
bspc config focused_border_color \#02db95 
bspc config normal_border_color \#6ce2e2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^2' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

